"""keep the order the programme prints its blocks in.

Revision ID: 084e41d59dc1
Revises: cf190f5ebd2b
Create Date: 2026-08-31 12:41:02.907286

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "084e41d59dc1"
down_revision: str | Sequence[str] | None = "cf190f5ebd2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "program_items",
        sa.Column("source_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("program_items", "source_order")
    # ### end Alembic commands ###
