"""give program_items a natural key.

Revision ID: 3f35acdc4c10
Revises: 7593dc4f45df
Create Date: 2026-08-30 18:40:14.561280

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f35acdc4c10"
down_revision: str | Sequence[str] | None = "7593dc4f45df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_program_items_level_subject_domain_title",
        "program_items",
        ["level", "subject_id", "domain_id", "title"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_program_items_level_subject_domain_title", "program_items", type_="unique"
    )
    # ### end Alembic commands ###
