"""give planned_sessions a natural key.

Revision ID: 521d22652f4c
Revises: ebfc3c648fd8
Create Date: 2026-08-31 12:21:22.520519

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "521d22652f4c"
down_revision: str | Sequence[str] | None = "ebfc3c648fd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_planned_sessions_day_slot_level",
        "planned_sessions",
        ["school_day_id", "timetable_slot_id", "level"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_planned_sessions_day_slot_level", "planned_sessions", type_="unique")
    # ### end Alembic commands ###
