"""add the school year data model.

Revision ID: 7593dc4f45df
Revises: 717a683bfee7
Create Date: 2026-08-30 18:05:54.953508

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7593dc4f45df"
down_revision: str | Sequence[str] | None = "717a683bfee7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "school_years",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("zone", sa.String(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "domains",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("level", sa.String(), server_default=sa.text("'commun'"), nullable=False),
        sa.CheckConstraint("level IN ('CM1', 'CM2', 'commun')", name="ck_domains_level"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "code", "level", name="uq_domains_subject_code_level"),
    )
    op.create_index(op.f("ix_domains_subject_id"), "domains", ["subject_id"], unique=False)
    op.create_table(
        "periods",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("school_year_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["school_year_id"], ["school_years.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_year_id", "code", name="uq_periods_year_code"),
    )
    op.create_index(op.f("ix_periods_school_year_id"), "periods", ["school_year_id"], unique=False)
    op.create_table(
        "school_holidays",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("school_year_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["school_year_id"], ["school_years.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_year_id", "label", name="uq_school_holidays_year_label"),
    )
    op.create_index(
        op.f("ix_school_holidays_school_year_id"),
        "school_holidays",
        ["school_year_id"],
        unique=False,
    )
    op.create_table(
        "sequences",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("objectives", sa.Text(), nullable=True),
        sa.Column("period_code", sa.String(), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint("level IN ('CM1', 'CM2', 'commun')", name="ck_sequences_level"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("method", "number", name="uq_sequences_method_number"),
    )
    op.create_index(op.f("ix_sequences_subject_id"), "sequences", ["subject_id"], unique=False)
    op.create_table(
        "program_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_file", sa.String(), nullable=False),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('french', coalesce(title, '') || ' ' || coalesce(description, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.CheckConstraint("level IN ('CM1', 'CM2', 'commun')", name="ck_program_items_level"),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_program_items_domain_id"), "program_items", ["domain_id"], unique=False
    )
    op.create_index(
        "ix_program_items_search_vector",
        "program_items",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_program_items_subject_id"), "program_items", ["subject_id"], unique=False
    )
    op.create_table(
        "sequence_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sequence_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("materials", sa.Text(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["sequence_id"], ["sequences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sequence_id", "number", name="uq_sequence_sessions_sequence_number"),
    )
    op.create_index(
        op.f("ix_sequence_sessions_sequence_id"), "sequence_sessions", ["sequence_id"], unique=False
    )
    op.create_table(
        "timetable_slots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("starts_at", sa.Time(), nullable=False),
        sa.Column("ends_at", sa.Time(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("domain_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.String(), server_default=sa.text("'commun'"), nullable=False),
        sa.Column("is_alternating", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("alternation_group", sa.String(), nullable=True),
        sa.CheckConstraint("day_of_week IN (1, 2, 3, 4, 5)", name="ck_timetable_slots_day_of_week"),
        sa.CheckConstraint("level IN ('CM1', 'CM2', 'commun')", name="ck_timetable_slots_level"),
        sa.CheckConstraint(
            "is_alternating = (alternation_group IS NOT NULL)",
            name="ck_timetable_slots_alternation",
        ),
        sa.CheckConstraint("starts_at < ends_at", name="ck_timetable_slots_time_range"),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "day_of_week", "starts_at", "level", name="uq_timetable_slots_day_start_level"
        ),
    )
    op.create_index(
        op.f("ix_timetable_slots_domain_id"), "timetable_slots", ["domain_id"], unique=False
    )
    op.create_index(
        op.f("ix_timetable_slots_subject_id"), "timetable_slots", ["subject_id"], unique=False
    )
    op.create_table(
        "weeks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("school_year_id", sa.UUID(), nullable=False),
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("number_in_period", sa.Integer(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["period_id"], ["periods.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_year_id"], ["school_years.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_year_id", "number", name="uq_weeks_year_number"),
        sa.UniqueConstraint("school_year_id", "starts_on", name="uq_weeks_year_starts_on"),
    )
    op.create_index(op.f("ix_weeks_period_id"), "weeks", ["period_id"], unique=False)
    op.create_index(op.f("ix_weeks_school_year_id"), "weeks", ["school_year_id"], unique=False)
    op.create_table(
        "school_days",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("week_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("is_off", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("off_reason", sa.String(), nullable=True),
        sa.CheckConstraint("day_of_week IN (1, 2, 3, 4, 5)", name="ck_school_days_day_of_week"),
        sa.ForeignKeyConstraint(["week_id"], ["weeks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_index(op.f("ix_school_days_week_id"), "school_days", ["week_id"], unique=False)
    op.create_table(
        "journal_revisions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("school_day_id", sa.UUID(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("snapshot_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("snapshot_after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), server_default=sa.text("'proposée'"), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('proposée', 'appliquée', 'rejetée')", name="ck_journal_revisions_status"
        ),
        sa.ForeignKeyConstraint(["school_day_id"], ["school_days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_revisions_school_day_id"),
        "journal_revisions",
        ["school_day_id"],
        unique=False,
    )
    op.create_table(
        "planned_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("school_day_id", sa.UUID(), nullable=False),
        sa.Column("timetable_slot_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("sequence_id", sa.UUID(), nullable=True),
        sa.Column("sequence_session_id", sa.UUID(), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("domain_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("objectives", sa.Text(), nullable=True),
        sa.Column("materials", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), server_default=sa.text("'planifiée'"), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("level IN ('CM1', 'CM2', 'commun')", name="ck_planned_sessions_level"),
        sa.CheckConstraint(
            "status IN ('planifiée', 'faite', 'reportée', 'annulée')",
            name="ck_planned_sessions_status",
        ),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_day_id"], ["school_days.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sequence_id"], ["sequences.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["sequence_session_id"], ["sequence_sessions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["timetable_slot_id"], ["timetable_slots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planned_sessions_domain_id"), "planned_sessions", ["domain_id"], unique=False
    )
    op.create_index(
        op.f("ix_planned_sessions_school_day_id"),
        "planned_sessions",
        ["school_day_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_planned_sessions_sequence_id"), "planned_sessions", ["sequence_id"], unique=False
    )
    op.create_index(
        op.f("ix_planned_sessions_sequence_session_id"),
        "planned_sessions",
        ["sequence_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_planned_sessions_subject_id"), "planned_sessions", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_planned_sessions_timetable_slot_id"),
        "planned_sessions",
        ["timetable_slot_id"],
        unique=False,
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("school_day_id", sa.UUID(), nullable=False),
        sa.Column("planned_session_id", sa.UUID(), nullable=True),
        sa.Column("discipline", sa.String(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("objectives", sa.Text(), nullable=True),
        sa.Column("bilan", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["planned_session_id"], ["planned_sessions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["school_day_id"], ["school_days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_entries_planned_session_id"),
        "journal_entries",
        ["planned_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_entries_school_day_id"), "journal_entries", ["school_day_id"], unique=False
    )
    op.create_table(
        "planned_session_program_items",
        sa.Column("planned_session_id", sa.UUID(), nullable=False),
        sa.Column("program_item_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["planned_session_id"], ["planned_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["program_item_id"], ["program_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("planned_session_id", "program_item_id"),
    )
    op.create_index(
        op.f("ix_planned_session_program_items_program_item_id"),
        "planned_session_program_items",
        ["program_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_planned_session_program_items_program_item_id"),
        table_name="planned_session_program_items",
    )
    op.drop_table("planned_session_program_items")
    op.drop_index(op.f("ix_journal_entries_school_day_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_planned_session_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_planned_sessions_timetable_slot_id"), table_name="planned_sessions")
    op.drop_index(op.f("ix_planned_sessions_subject_id"), table_name="planned_sessions")
    op.drop_index(op.f("ix_planned_sessions_sequence_session_id"), table_name="planned_sessions")
    op.drop_index(op.f("ix_planned_sessions_sequence_id"), table_name="planned_sessions")
    op.drop_index(op.f("ix_planned_sessions_school_day_id"), table_name="planned_sessions")
    op.drop_index(op.f("ix_planned_sessions_domain_id"), table_name="planned_sessions")
    op.drop_table("planned_sessions")
    op.drop_index(op.f("ix_journal_revisions_school_day_id"), table_name="journal_revisions")
    op.drop_table("journal_revisions")
    op.drop_index(op.f("ix_school_days_week_id"), table_name="school_days")
    op.drop_table("school_days")
    op.drop_index(op.f("ix_weeks_school_year_id"), table_name="weeks")
    op.drop_index(op.f("ix_weeks_period_id"), table_name="weeks")
    op.drop_table("weeks")
    op.drop_index(op.f("ix_timetable_slots_subject_id"), table_name="timetable_slots")
    op.drop_index(op.f("ix_timetable_slots_domain_id"), table_name="timetable_slots")
    op.drop_table("timetable_slots")
    op.drop_index(op.f("ix_sequence_sessions_sequence_id"), table_name="sequence_sessions")
    op.drop_table("sequence_sessions")
    op.drop_index(op.f("ix_program_items_subject_id"), table_name="program_items")
    op.drop_index(
        "ix_program_items_search_vector", table_name="program_items", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_program_items_domain_id"), table_name="program_items")
    op.drop_table("program_items")
    op.drop_index(op.f("ix_sequences_subject_id"), table_name="sequences")
    op.drop_table("sequences")
    op.drop_index(op.f("ix_school_holidays_school_year_id"), table_name="school_holidays")
    op.drop_table("school_holidays")
    op.drop_index(op.f("ix_periods_school_year_id"), table_name="periods")
    op.drop_table("periods")
    op.drop_index(op.f("ix_domains_subject_id"), table_name="domains")
    op.drop_table("domains")
    op.drop_table("subjects")
    op.drop_table("school_years")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
