"""let a seance carry what its methodo lays out.

Revision ID: cf190f5ebd2b
Revises: 521d22652f4c
Create Date: 2026-08-31 12:38:50.919328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf190f5ebd2b"
down_revision: str | Sequence[str] | None = "521d22652f4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("planned_sessions", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("planned_sessions", "content")
    # ### end Alembic commands ###
