"""record the domaine a sequence belongs to.

Revision ID: ebfc3c648fd8
Revises: 3f35acdc4c10
Create Date: 2026-08-30 19:18:22.436888

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebfc3c648fd8"
down_revision: str | Sequence[str] | None = "3f35acdc4c10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sequences", sa.Column("domain_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_sequences_domain_id"), "sequences", ["domain_id"], unique=False)
    op.create_foreign_key(
        "sequences_domain_id_fkey",
        "sequences",
        "domains",
        ["domain_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sequences_domain_id_fkey", "sequences", type_="foreignkey")
    op.drop_index(op.f("ix_sequences_domain_id"), table_name="sequences")
    op.drop_column("sequences", "domain_id")
    # ### end Alembic commands ###
