"""Matières, domaines, and the items of the official CM1/CM2 curriculum.

``program_items`` are filled from ``docs/programme-cm1-cm2.pdf`` in Phase 2. The
full-text search column is generated by Postgres so it can never fall out of step
with the text it indexes.
"""

import uuid
from datetime import datetime
from typing import Any, ClassVar

from sqlalchemy import (
    Boolean,
    Column,
    Computed,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlmodel import Field, SQLModel

from core.models.base import (
    created_at_column,
    enum_check,
    enum_default,
    reference,
    updated_at_column,
    uuid_primary_key,
)
from core.models.level import Level

SEARCH_DOCUMENT = "to_tsvector('french', coalesce(title, '') || ' ' || coalesce(description, ''))"


class Subject(SQLModel, table=True):
    """A matière, with the colour it is drawn in."""

    __tablename__: ClassVar[str] = "subjects"

    id: uuid.UUID = uuid_primary_key()
    created_at: datetime = created_at_column()
    updated_at: datetime = updated_at_column()

    code: str = Field(sa_column=Column(String, nullable=False, unique=True))
    label: str = Field(sa_column=Column(String, nullable=False))
    color: str = Field(sa_column=Column(String, nullable=False))


class Domain(SQLModel, table=True):
    """A domaine: a subdivision of a matière, optionally specific to one niveau."""

    __tablename__: ClassVar[str] = "domains"
    __table_args__: ClassVar[tuple] = (
        UniqueConstraint("subject_id", "code", "level", name="uq_domains_subject_code_level"),
        enum_check("domains", "level", Level),
    )

    id: uuid.UUID = uuid_primary_key()
    created_at: datetime = created_at_column()
    updated_at: datetime = updated_at_column()

    subject_id: uuid.UUID = reference("subjects.id")
    code: str = Field(sa_column=Column(String, nullable=False))
    label: str = Field(sa_column=Column(String, nullable=False))
    level: Level = Field(
        sa_column=Column(String, nullable=False, server_default=enum_default(Level.COMMUN)),
        default=Level.COMMUN,
    )


class ProgramItem(SQLModel, table=True):
    """One institutional learning objective, traceable back to its page in the source PDF."""

    __tablename__: ClassVar[str] = "program_items"
    __table_args__: ClassVar[tuple] = (
        enum_check("program_items", "level", Level),
        Index("ix_program_items_search_vector", "search_vector", postgresql_using="gin"),
    )

    id: uuid.UUID = uuid_primary_key()
    created_at: datetime = created_at_column()
    updated_at: datetime = updated_at_column()

    level: Level = Field(sa_column=Column(String, nullable=False))
    subject_id: uuid.UUID = reference("subjects.id")
    domain_id: uuid.UUID | None = reference("domains.id", nullable=True, ondelete="SET NULL")
    title: str = Field(sa_column=Column(Text, nullable=False))
    description: str | None = Field(sa_column=Column(Text, nullable=True), default=None)
    source_file: str = Field(sa_column=Column(String, nullable=False))
    source_page: int | None = Field(sa_column=Column(Integer, nullable=True), default=None)
    needs_review: bool = Field(
        sa_column=Column(Boolean, nullable=False, server_default=text("false")), default=False
    )
    search_vector: Any | None = Field(
        sa_column=Column(TSVECTOR, Computed(SEARCH_DOCUMENT, persisted=True), nullable=True),
        default=None,
    )
