"""Séances planifiées: one créneau of the timetable, instantiated on one jour de classe.

Generated by the deterministic planner in Phase 3.
"""

import uuid
from datetime import datetime
from typing import ClassVar

from sqlalchemy import UUID, Column, ForeignKey, Integer, String, Text, text
from sqlmodel import Field, SQLModel

from core.models.base import (
    created_at_column,
    enum_check,
    enum_default,
    reference,
    updated_at_column,
    uuid_primary_key,
)
from core.models.level import Level
from core.models.status import SessionStatus


class PlannedSession(SQLModel, table=True):
    """What is taught in one créneau on one jour de classe."""

    __tablename__: ClassVar[str] = "planned_sessions"
    __table_args__: ClassVar[tuple] = (
        enum_check("planned_sessions", "level", Level),
        enum_check("planned_sessions", "status", SessionStatus),
    )

    id: uuid.UUID = uuid_primary_key()
    created_at: datetime = created_at_column()
    updated_at: datetime = updated_at_column()

    school_day_id: uuid.UUID = reference("school_days.id")
    timetable_slot_id: uuid.UUID = reference("timetable_slots.id")
    level: Level = Field(sa_column=Column(String, nullable=False))
    sequence_id: uuid.UUID | None = reference("sequences.id", nullable=True, ondelete="SET NULL")
    sequence_session_id: uuid.UUID | None = reference(
        "sequence_sessions.id", nullable=True, ondelete="SET NULL"
    )
    subject_id: uuid.UUID | None = reference("subjects.id", nullable=True, ondelete="SET NULL")
    domain_id: uuid.UUID | None = reference("domains.id", nullable=True, ondelete="SET NULL")
    title: str = Field(sa_column=Column(Text, nullable=False))
    objectives: str | None = Field(sa_column=Column(Text, nullable=True), default=None)
    materials: str | None = Field(sa_column=Column(Text, nullable=True), default=None)
    status: SessionStatus = Field(
        sa_column=Column(
            String, nullable=False, server_default=enum_default(SessionStatus.PLANIFIEE)
        ),
        default=SessionStatus.PLANIFIEE,
    )
    position: int = Field(sa_column=Column(Integer, nullable=False, server_default=text("0")))


class PlannedSessionProgramItem(SQLModel, table=True):
    """Links a séance to the items de programme it covers."""

    __tablename__: ClassVar[str] = "planned_session_program_items"

    planned_session_id: uuid.UUID = Field(
        sa_column=Column(
            UUID, ForeignKey("planned_sessions.id", ondelete="CASCADE"), primary_key=True
        )
    )
    program_item_id: uuid.UUID = Field(
        sa_column=Column(
            UUID, ForeignKey("program_items.id", ondelete="CASCADE"), primary_key=True, index=True
        )
    )
